### ISSUE TITLE
GitLab SSH Repository Update Error

### ISSUE THREAD

**Issue by online-sanaullah** [OCA/runbot-addons#149] opened 2018-03-21 11:35 UTC
Hi,

Whenever I try to update a repository from Gitlab using SSH I get the following error.

> Traceback (most recent call last):
> File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 544, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 581, in dispatch
>     result = self._call_function(**self.params)
>   File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 317, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 314, in checked_call
>     return self.endpoint(*a, **kw)
>   File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 810, in __call__
>     return self.method(*args, **kw)
>   File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 410, in response_wrap
>     response = f(*args, **kw)
>   File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 948, in call_button
>     action = self._call_kw(model, method, args, {})
>   File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 936, in _call_kw
>     return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
>     return old_api(self, *args, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 439, in old_api
>     result = new_api(recs, *args, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 443, in new_api
>     result = [method(rec, *args, **kwargs) for rec in self]
>   File "/mnt/runbot-addons/runbot_gitlab/models/runbot_repo.py", line 79, in gitlab_func
>     return func(self, *args, **kwargs)
>   File "/mnt/runbot-addons/runbot_gitlab/models/runbot_repo.py", line 168, in update
>     'search': self.gitlab_name.split('/')[-1],
>   File "/mnt/runbot-addons/runbot_gitlab/models/runbot_repo.py", line 136, in _query_gitlab_api
>     ignore_errors=ignore_errors)
>   File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 266, in wrapper
>     return new_api(self, *args, **kwargs)
>   File "/mnt/runbot-addons/runbot_gitlab/models/runbot_repo.py", line 154, in _query_gitlab
>     headers=headers)
>   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 60, in get
>     return request('get', url, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 420, in send
>     raise SSLError(e, request=request)
> SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:581)

**Comment by moylop260** [comment] 2018-06-04 17:42
Won't fix since that we can't reproduce it.
Feel free to re-open it with more details about.

**Closed as completed by moylop260** 2018-06-04 17:42 UTC
