### ISSUE TITLE
Runbot and private repositories

### ISSUE THREAD

**Issue by domatix-dev** [OCA/runbot-addons#46] opened 2015-07-06 09:40 UTC
Someone has used private repository with runbot.

I was trying but I'm not able to do it.

I just generate a personal access token, and system user of runbot has ssh key in github user...

When I try to update repository had this error:

```
Traceback (most recent call last):
  File "/home/odoo/server/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/server/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/server/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/server/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/odoo/server/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/server/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/server/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/server/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/instances/base/addons/runbot/runbot.py", line 247, in update
    self.update_git(cr, uid, repo)
  File "/home/odoo/server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/instances/base/addons/runbot/runbot.py", line 265, in update_git
    git_refs = repo.git(['for-each-ref', '--format', fmt, '--sort=-committerdate', 'refs/heads', 'refs/pull'])
  File "/home/odoo/server/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/server/openerp/api.py", line 546, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/home/odoo/instances/base/addons/runbot/runbot.py", line 214, in git
    return subprocess.check_output(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['git', u'--git-dir=/home/odoo/instances/base/addons/runbot/static/repo/https___github.com_XXX_YYY.git', 'for-each-ref', '--format', '%(refname)%00%(objectname)%00%(committerdate:iso8601)%00%(authorname)%00%(subject)%00%(committername)', '--sort=-committerdate', 'refs/heads', 'refs/pull']' returned non-zero exit status 128
```

Where 'https___github.com_XXX_YYY.git' is a private repository

**Comment by nhomar** [comment] 2015-07-06 10:19
@domatix-dev are you able to make git clone of such repository with the user which is running odoo directly from the shell?

Which version commit do you have?

We use it perfectly like a charm with private repositories.

Regards.

**Comment by domatix-dev** [comment] 2015-07-06 10:42
I can clone, but ask me for user and password.

**Comment by domatix-dev** [comment] 2015-07-06 10:49
I was allow to do in runbot If I cached my password first with:

git config --global credential.helper cache

But this solution is temporal, after timeout expired git will ask for user and password other time.

My repository is private repository of my group, no personal repository.

**Comment by bwrsandman** [comment] 2015-07-06 15:21
Try using the `git@github.com:XXX/YYY` form to clone via ssh. It won't ask your password if the ssh keys have been defined.

**Comment by domatix-dev** [comment] 2015-07-06 15:25
Cloning via ssh raise other error because runbot is not able to get url.

```
Traceback (most recent call last):
  File "/home/odoo/server/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/server/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/server/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/server/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/odoo/server/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/server/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/server/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/server/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/server/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/instances/base/addons/runbot_gitlab/models/runbot_repo.py", line 159, in create
    repo_id.id,
  File "/home/odoo/instances/base/addons/runbot_gitlab/models/runbot_repo.py", line 144, in set_gitlab_ci_conf
    requests.put(url, data=data, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 99, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)
SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

thanks a lot

**Comment by bwrsandman** [comment] 2015-07-06 15:32
try on your runbot server as the same user to do a `git clone git@github.com:XXX/YYY` and see what it tells you perhaps your system doesn't have the proper certificates.

**Comment by domatix-dev** [comment] 2015-07-06 15:43
Same user in runbot server can do:
- git clone git@github.com:XXX/YYY, with my ssh key, and key has no passphrase, in ssh no problem.
- git clone http:... ask for user and password, if I do it first on server and cached my password then it works on odoo runbot.

I think the problem is that runbot addons asume that git user name is on repo url, but my repo is owned by a group, no by an user. So runbot try to use XXX as user name, but XXX is the group name. Is it possible?

@nhomar Did you use runbot for repositories owned by a group?

If it is the problem, maybe we need to add a field on repository to specify the user name if repo is owned by a group.

**Comment by bwrsandman** [comment] 2015-07-06 15:46
Groups and users are interchangeable as far as I know that shouldn't change things.

**Comment by bwrsandman** [comment] 2015-07-06 15:47
Are you using ubuntu by any chance?

**Comment by domatix-dev** [comment] 2015-07-06 15:48
Yes, ubuntu server 14.04

**Comment by bwrsandman** [comment] 2015-07-06 15:50
What version?

**Comment by domatix-dev** [comment] 2015-07-06 15:50
sorry.. update comment.

ubuntu server 14.04

**Comment by bwrsandman** [comment] 2015-07-06 15:55
There is a ssl bug in ubuntu 12.04 that looks a little like that... I don't really know what the problem is, you can try looking at the error you're getting about the certificates. Seems like a general python error.

You can also ask the maintainers of runbot at https://github.com/odoo/odoo-extra or email them as they don't always answer on github.

**Comment by domatix-dev** [comment] 2015-07-06 16:09
Ok, thanks a lot.

The ssl error really is not the problem, this error raises from runbot_gitlab module, when is trying to get gitlab_ci url from ssh repo direction.

**Comment by bwrsandman** [comment] 2015-07-06 16:24
It is trying to do the following command which you can run in command line.

```
curl -X PUT http://RUNBOT_DOMAIN/gitlab-ci/REPO_ID -d token=TOKEN -d project_url=PROJECT_URL -H "PRIVATE-TOKEN: TOKEN"
```

Can you do this command successfully?

```
curl http://RUNBOT_DOMAIN/gitlab-ci/REPO_ID -H "PRIVATE-TOKEN: GITLAB_TOKEN"
```

Try this even

```
curl http://RUNBOT_DOMAIN/gitlab-ci/projects -H "PRIVATE-TOKEN: GITLAB_TOKEN"
```

**Comment by domatix-dev** [comment] 2015-07-07 07:35
Thanks a lot for yout support.

Second command is ok, get me that my user is correct user.

First command I don't know what is the repo_id.

In any case, this error raise only on ssh mode.

**Comment by domatix-dev** [comment] 2015-07-07 07:42
Sorry, I just find repo_id with:

```
curl http://DOMAIN/api/v3/projects -H "PRIVATE-TOKEN: GITLAB_TOKEN"
```

and read better the message, it's a redirection, it's show me:

```
<html><body>You are being <a href="http://DOMAIN/users/sign_in">redirected</a>.</body></html>
```

**Comment by OSguard** [comment] 2016-03-01 09:23
can we close this?

**Closed as completed** 2018-06-04 17:32 UTC
