### ISSUE TITLE
Dockerized Runbot - Missing Image

### ISSUE THREAD

**Issue by lasley** [OCA/runbot-addons#111] opened 2016-12-01 15:55 UTC
Randomly Runbot is failing with the following message in the all log (from [Runbot build](https://runbot.odoo-community.org/runbot/build/3274021) & https://github.com/OCA/server-tools/pull/611#issuecomment-264187178):

```
Unable to find image 'oca-server-tools:9bb61bf_3' locally
Pulling repository oca-server-tools
time="2016-12-01T14:47:40Z" level=fatal msg="Error: image library/oca-server-tools:9bb61bf_3 not found" 
```

Build looks fine:
```
Sending build context to Docker daemon 24.06 kB

Sending build context to Docker daemon 
Step 0 : FROM vauxoo/odoo-80-image-shippable-auto
latest: Pulling from vauxoo/odoo-80-image-shippable-auto
600f68629688: Already exists
f55680a9f435: Already exists
45aa5b54eb26: Already exists
04e81abeea1d: Already exists
3b8d72e434f8: Already exists
08fe2ef22779: Already exists
45dbfe2621e6: Already exists
fd8638d565b9: Already exists
f9fd3e6c6287: Already exists
e47fd885d98c: Already exists
cb57ee658fe2: Already exists
3d7fb6dd9bff: Already exists
504d62bce149: Already exists
62f906607b33: Already exists
0b0367bd58fd: Already exists
de3c0ca761e0: Already exists
bc1a7c99dee1: Already exists
30a5e802b61e: Already exists
0bf9d24aedcc: Already exists
0f25fe6f3f6c: Already exists
Digest: sha256:73a80d28d41b0c2d5a01951dbe41693a29651a677727c8c9f76db601ee745b4d
Status: Image is up to date for vauxoo/odoo-80-image-shippable-auto:latest
 ---> 0f25fe6f3f6c
Step 1 : ADD files/entrypoint.sh /entrypoint.sh
 ---> 27dedcc9c03a
Removing intermediate container 2713f9a53469
Step 2 : RUN chown -R root:root /entrypoint.sh
 ---> Running in 8d0511a98f0f
 ---> 5016bcedf285
Removing intermediate container 8d0511a98f0f
Step 3 : ADD files/rvm_env.sh /rvm_env.sh
 ---> 04054f378bf0
Removing intermediate container 84ae5c68b6d7
Step 4 : RUN chown -R root:root /rvm_env.sh
 ---> Running in 409969779aa6
 ---> dcb1f4c83687
Removing intermediate container 409969779aa6
Step 5 : ENV HOME /root
 ---> Running in 45d3a76bb504
 ---> 60be03911c08
Removing intermediate container 45d3a76bb504
Step 6 : ADD .ssh $HOME/.ssh
 ---> 91103488411c
Removing intermediate container bf8be5a0f0d4
Step 7 : RUN chown -R root:root $HOME/.ssh
 ---> Running in 0141e38d069a
 ---> 4dd10cd041c1
Removing intermediate container 0141e38d069a
Step 8 : ADD ./files/install /install
 ---> f4c4d144c8dc
Removing intermediate container 9ccfe15a56ca
Step 9 : RUN chown -R root:root /install
 ---> Running in 912582e37517
 ---> 4872d95c52a3
Removing intermediate container 912582e37517
Step 10 : ADD ./files/script /script
 ---> ddc8d6c884d6
Removing intermediate container 64e73448aab5
Step 11 : RUN chown -R root:root /script
 ---> Running in ce6bb113ec0b
 ---> 5802b0b6f3a4
Removing intermediate container ce6bb113ec0b
Step 12 : ADD ./files/after_success /after_success
 ---> 699611c743fb
Removing intermediate container bc26667257ba
Step 13 : RUN chown -R root:root /after_success
 ---> Running in 33e01acdeb4d
 ---> 528c9c78acf2
Removing intermediate container 33e01acdeb4d
Step 14 : RUN apt-get update; apt-get install expect-dev python-lxml
 ---> Running in b173988bb94a
Get:1 http://deb.nodesource.com trusty InRelease [3,914 B]
Ign http://archive.ubuntu.com trusty InRelease
Get:2 http://ppa.launchpad.net trusty InRelease [15.5 kB]
Get:3 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]
Get:4 http://archive.ubuntu.com trusty-security InRelease [65.9 kB]
Get:5 http://apt.postgresql.org trusty-pgdg InRelease [46.5 kB]
Get:6 http://ppa.launchpad.net trusty InRelease [15.4 kB]
Get:7 http://ppa.launchpad.net trusty InRelease [15.5 kB]
Get:8 http://archive.ubuntu.com trusty Release.gpg [933 B]
Get:9 http://archive.ubuntu.com trusty Release [58.5 kB]
Get:10 http://deb.nodesource.com trusty/main amd64 Packages [964 B]
Get:11 http://archive.ubuntu.com trusty-updates/main amd64 Packages [1,153 kB]
Get:12 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [503 kB]
Get:13 http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages [15.2 kB]
Get:14 http://archive.ubuntu.com trusty-security/main amd64 Packages [694 kB]
Get:15 http://archive.ubuntu.com trusty-security/universe amd64 Packages [189 kB]
Get:16 http://archive.ubuntu.com trusty-security/multiverse amd64 Packages [4,015 B]
Get:17 http://ppa.launchpad.net trusty/main amd64 Packages [2,941 B]
Get:18 http://ppa.launchpad.net trusty/main amd64 Packages [3,419 B]
Get:19 http://ppa.launchpad.net trusty/main amd64 Packages [20.5 kB]
Get:20 http://archive.ubuntu.com trusty/main amd64 Packages [1,743 kB]
Get:21 http://archive.ubuntu.com trusty/universe amd64 Packages [7,589 kB]
Get:22 http://archive.ubuntu.com trusty/multiverse amd64 Packages [169 kB]
Get:23 http://apt.postgresql.org trusty-pgdg/main amd64 Packages [112 kB]
Fetched 12.5 MB in 2s (6,188 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
expect-dev is already the newest version.
Suggested packages:
  python-lxml-dbg
The following NEW packages will be installed:
  python-lxml
0 upgraded, 1 newly installed, 0 to remove and 16 not upgraded.
Need to get 629 kB of archives.
After this operation, 2,542 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty-updates/main python-lxml amd64 3.3.3-1ubuntu0.1 [629 kB]
Fetched 629 kB in 0s (4,902 kB/s)
Selecting previously unselected package python-lxml.
(Reading database ... 39868 files and directories currently installed.)
Preparing to unpack .../python-lxml_3.3.3-1ubuntu0.1_amd64.deb ...
Unpacking python-lxml (3.3.3-1ubuntu0.1) ...
Setting up python-lxml (3.3.3-1ubuntu0.1) ...
 ---> 77322ac18943
Removing intermediate container b173988bb94a
Step 15 : USER root
 ---> Running in 722716603af6
 ---> 02a34d2bbec1
Removing intermediate container 722716603af6
Step 16 : ENV TRAVIS_REPO_SLUG OCA/server-tools
 ---> Running in 9aa1740ad6e9
 ---> 109f18276828
Removing intermediate container 9aa1740ad6e9
Step 17 : ENV TRAVIS_BUILD_DIR ${HOME}/build/${TRAVIS_REPO_SLUG}
 ---> Running in f4e3fc40c0e4
 ---> c47e48335273
Removing intermediate container f4e3fc40c0e4
Step 18 : RUN git init ${TRAVIS_BUILD_DIR}     && cd ${TRAVIS_BUILD_DIR}     && git remote add origin https://github.com/OCA/server-tools     && git fetch --update-head-ok -p origin '+refs/pull/611/head:refs/pull/611'     && git checkout -qf pull/611     && git config --global user.email "None"     && git config --global user.name "None"     && echo 1
 ---> Running in 01afa7be37a7
Initialized empty Git repository in /root/build/OCA/server-tools/.git/
[91mFrom https://github.com/OCA/server-tools
 * [new ref]         refs/pull/611/head -> refs/pull/611
[0m1
 ---> 29fa9d593198
Removing intermediate container 01afa7be37a7
Step 19 : RUN cat ${HOME}/.ssh/id_rsa.pub | tee -a ${HOME}/.ssh/authorized_keys
 ---> Running in bc2eb8584647
[91mcat: /root/.ssh/id_rsa.pub[0m[91m: No such file or directory
[0m ---> c7d44d89b992
Removing intermediate container bc2eb8584647
Step 20 : ENV VERSION "9.0" TESTS "0" LINT_CHECK "0" TRANSIFEX "0" TRANSIFEX_USER 'transbot@odoo-community.org' TESTS "1" ODOO_REPO "odoo/odoo"
 ---> Running in 8f35eff004c8
 ---> 2f19ae73cc93
Removing intermediate container 8f35eff004c8
Step 21 : WORKDIR ${TRAVIS_BUILD_DIR}
 ---> Running in c869d1f6e120
 ---> 70cef9d9f10b
Removing intermediate container c869d1f6e120
Step 22 : RUN /bin/bash -c "source /rvm_env.sh && /install"
 ---> Running in 100f5687a815
[91m/install: line 26: getaddons.py: command not found
[0m[91mCloning into '/root/maintainer-quality-tools'...
[0m/usr/bin/lessc -> /usr/lib/node_modules/less/bin/lessc
/usr/lib
â”œâ”€â”€ less@2.7.1 
â””â”€â”€ less-plugin-clean-css@1.5.1 

Using Odoo from cache /.repo_requirements
[91mFrom https://github.com/odoo/odoo
 * branch            9.0        -> FETCH_HEAD
[0m[91m * [new branch]      9.0        -> odoo/9.0
[0mRequirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages
Getting addons dependencies
Content of /root:
total 16
drwxr-xr-x 3 root root 4096 Dec  1 14:45 build
drwxr-xr-x 2 root root 4096 Dec  1 14:45 dependencies
drwxr-xr-x 8 root root 4096 Dec  1 14:45 maintainer-quality-tools
lrwxrwxrwx 1 root root   24 Dec  1 14:45 odoo-9.0 -> /.repo_requirements/odoo
drwxr-xr-x 3 root root 4096 Nov 28 17:39 tools
Content of /root/dependencies:
total 0
[91mln: failed to create symbolic link â€˜/openerp/addons/server_environment_filesâ€™[0m[91m: No such file or directory
[0mtime="2016-12-01T14:45:51Z" level=info msg="The command [/bin/sh -c /bin/bash -c \"source /rvm_env.sh && /install\"] returned a non-zero code: 1" 
```

**Comment by lasley** [comment] 2016-12-01 16:17
I've experienced this on my own Runbot before too. I can fairly easily replicate the issue by pushing to the same branch a bunch of times.

What I think is happening is that our sandbox between builds is being broken - a previous build is stopping or deleting an image/container when it is done, but a later build is still using it.

**Comment by moylop260** [comment] 2016-12-01 16:21
What version of docker you have installed in your own Runbot?

Maybe is a symbolic link issue (or maybe in your case a `move` file issue) from docker

**Comment by lasley** [comment] 2016-12-01 16:21
Docker version 1.12.3, build 6b644ec

Docker-gc 0.1.1 (just in case)

**Comment by moylop260** [comment] 2016-12-01 16:23
The projects with the same issue Are there `ln` or `mv` commands?

**Comment by lasley** [comment] 2016-12-01 16:29
Like in the code? Nah no shell or file manipulations. I'm pretty sure it's not the code, because I have had instances in which the PR build breaks but the branch build does not. Merging the code or creating/pushing a new branch will typically yield a 🍏  too.

Interesting thing is - once it happens for a branch, it'll just keep happening. That branch is basically toast for the remainder of Runbot eternity.

More examples can be seen on [my runbot, vertical-medical repo](https://runbot.laslabs.io/runbot/repo/git-github-com-laslabs-vertical-medical-git-41) Build `39` and `medical_physician`. This example is actually one of the first times I have seen both the PR and Branch build fail at the same time.

For referencing the example, [this is the diff causing issues](https://github.com/laslabs/vertical-medical/pull/39/files).

**Comment by moylop260** [comment] 2016-12-01 17:05
The case for build 39 is a little different.
Because the error is in clone dependencies:

```bash
Getting addons dependencies
[91mfatal: Remote branch origin/feature/10.0/product_service_duration not found in upstream origin
[0m[91mTraceback (most recent call last):
  File "/root/maintainer-quality-tools/travis/clone_oca_dependencies", line 123, in <module>
[0m[91m    run(deps_checkout_dir, build_dir)
  File "/root/maintainer-quality-tools/travis/clone_oca_dependencies", line 98, in run
    url, branch)
  File "/root/maintainer-quality-tools/travis/clone_oca_dependencies", line 66, in git_checkout
    subprocess.check_call(command)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
[0m[91msubprocess.CalledProcessError[0m[91m: Command '['git', 'clone', '-q', 'https://github.com/laslabs/product-attribute.git', '-b', 'origin/feature/10.0/product_service_duration', '/root/dependencies/product-attribute']' returned non-zero exit status 128[0m[91m
[0mThe command '/bin/sh -c /install' returned a non-zero code: 1
```

Running the same command: `git clone -q https://github.com/laslabs/product-attribute.git -b origin/feature/10.0/product_service_duration` I had the same output locally:
![screen shot 2016-12-01 at 11 07 36 am](https://cloud.githubusercontent.com/assets/6644187/20803776/02d0e3de-b7b6-11e6-9656-ff645d74c6fb.png)

**Comment by moylop260** [comment] 2016-12-01 17:09
...I mean, the issue was [this line](https://github.com/laslabs/vertical-medical/pull/39/files#diff-58bf4ef7bb17e0cabe9c102156155697R2)

You could fix it:
```diff
+product-attribute https://github.com/laslabs/product-attribute.git origin/feature/10.0/product_service_duration
-product-attribute https://github.com/laslabs/product-attribute.git feature/10.0/product_service_duration
```

Running locally:
`git clone -q https://github.com/laslabs/product-attribute.git -b feature/10.0/product_service_duration`
Worked fine!

Do you have another example without clone issue?

**Comment by lasley** [comment] 2016-12-01 17:12
Ahh well crap so my example was bad. That also makes sense why it's also the only one I've seen fail on both branches, so I should have known it was effed. 

Here's another, same Runbot just use the `40` and `medical_center` branches (they're the same branch, just the difference between the PR and non). I probably can find a few others by grepping the logs on filesystem if we need more. It happens often enough that my juniors gave a 🎉  when they saw this issue created.

**Comment by lasley** [comment] 2016-12-01 17:16
Interesting now that I'm looking, that is a clone issue too - Github timeout (which also makes sense why I've seen it only with parallel branches). And the one reported in the https://github.com/OCA/server-tools/pull/611#issuecomment-264187178 is actually an issue with the environment.

```
[91mln: failed to create symbolic link ‘/openerp/addons/server_environment_files’[0m[91m: No such file or directory
[0mtime="2016-12-01T14:45:51Z" level=info msg="The command [/bin/sh -c /bin/bash -c \"source /rvm_env.sh && /install\"] returned a non-zero code: 1" 
```

So really it seems in all instances, the build is just failing before the tests. I'm curious as to the other reasons it has been failing like this now.

**Comment by moylop260** [comment] 2016-12-01 17:22
The real fail is creating symbolic link `/openerp/addons/server_environment_files No such file or directory`

That line is in `/install` section from [travis.yml](https://github.com/OCA/server-tools/blob/c9d97b9cb4ee9f46ed9be21a021d9b9738e8c31c/.travis.yml#L35)

The command should be: `ln -s ${TRAVIS_BUILD_DIR}/server_environment_files_sample ${TRAVIS_BUILD_DIR}/server_environment_files`

But the path received was `/openerp/addons/server_environment_files`
Then `TRAVIS_BUILD_DIR`was equal to `/openerp/addons`?

**Comment by lasley** [comment] 2016-12-01 17:29
Yeah what the heck? I remember this one from the other day too now:
* https://runbot.odoo-community.org/runbot/build/3273949
* https://github.com/OCA/server-tools/pull/623

**Comment by moylop260** [comment] 2016-12-01 17:32
I can confirm that this issue is because we have 2 server with different environments.
Using rebuilds of PR 611 from [runbot/server-tools](https://runbot.odoo-community.org/runbot/repo/github-com-oca-server-tools-149):

![build](https://cloud.githubusercontent.com/assets/6644187/20804714/889648ee-b7b9-11e6-8409-994d3079f597.png)


@gurneyalex Could you help us to get the differences between runbot2 (fine!) and runbot1 (failing), please?
  - `docker version`
  - `travisfile2dockerfile --version`
  - Sha of runbot-addons and odoo-extra

**Comment by moylop260** [comment] 2016-12-01 18:00
Or wait this looks like as a flaky error

It's not a runbot1 vs runbot2 error because I have the same issue with runbot2 too in a few cases:
![screen shot 2016-12-01 at 12 01 54 pm](https://cloud.githubusercontent.com/assets/6644187/20805732/a5a309fa-b7bd-11e6-8775-745973d3be2e.png)

**Comment by moylop260** [comment] 2016-12-01 18:21
I saw differences between a test_10_job.log fine and other one failing:

| step | [job_10_test_base-red.txt](https://github.com/OCA/runbot-addons/files/625480/job_10_test_base-red.txt) 🔴   | [job_10_test_base-green.txt](https://github.com/OCA/runbot-addons/files/625481/job_10_test_base-green.txt) 🍏  |
|------|-----|-------|
| 19 <br/> `RUN cat ${HOME}/.ssh/id_rsa.pub | tee -a ${HOME}/.ssh/authorized_keys` | `cat: /root/.ssh/id_rsa.pub: No such file or directory` | `cat: /root/.ssh/id_rsa.pub: No such file or directory` (Without differences)
|  21 <br/> `RUN /bin/bash -c "source /rvm_env.sh && /install"`   |   `/install: line 61: getaddons.py: command not found` <br/> `/install: line 66: getaddons.py: command not found` <br/> `Cloning into '/root/maintainer-quality-tools'...` |   `Cloning into '/root/maintainer-quality-tools'...`    |

**Comment by moylop260** [comment] 2016-12-01 18:24
@lasley 
I think are issues related with a old docker version installed from OCA server.

You have installed a newest, then we can confirm or reject this theory if you have a similar case of this issue in your runbot.

**Comment by lasley** [comment] 2016-12-01 18:25
@moylop260 I did not find this specific issue in my log grep's. The step you noted is the RVM install though, and I haven't updated my prod runbot to our new changes yet. Shall I do that and monitor?

**Comment by Garamotte** [comment] 2016-12-01 18:33
If it can help, looking at OCA's runbot server, I think the first error in the logs is:
```
Step 19 : RUN cat ${HOME}/.ssh/id_rsa.pub | tee -a ${HOME}/.ssh/authorized_keys
 ---> Running in c323e29eba97
[91mcat: /root/.ssh/id_rsa.pub[0m[91m: No such file or directory
[0m ---> 2c13cdafa356
Removing intermediate container c323e29eba97
```
This error can be seen [here](https://runbot.odoo-community.org/runbot/static/build/3274032-611-9bb61b/logs/job_10_test_base.txt) and [here](https://runbot2.odoo-community.org/runbot/static/build/3274021-611-9bb61b/logs/job_10_test_base.txt)

**Comment by moylop260** [comment] 2016-12-01 18:34
I saw that the real issue is a command not found from step 21

Could you run in your runbot server the following command `rgrep "command not found" odoo-extra/runbot/static/build/*/logs --include=job_10_test_base.txt`please?

**Comment by moylop260** [comment] 2016-12-01 18:37
@sylvain-garancher
Thanks for tip.

That is not the real error because we have that output from green case and red one.  (I just updated my table with that case)

**Comment by moylop260** [comment] 2016-12-02 02:51
@gurneyalex 
I remember issues related with filesystem for old docker version (But I don't have the reference now)
Could we upgrade `docker 1.6.2` to `1.12.2`?

FYI our http://runbot.vauxoo.com has working fine with the following version:
```bash
...
Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:29:41 2016
 OS/Arch:      linux/amd64
```

For this case where a old version of docker is installed you will need apply a manual change base on [docker-release-1.12.2](https://github.com/docker/docker/releases/tag/v1.12.2) documentation.

![release](https://cloud.githubusercontent.com/assets/6644187/20821297/117fc32c-b807-11e6-9750-579499ca9072.png)


For new version of docker they are using `systemctl` and is required a `task=inifinity` configuration to avoid the error `Running in 75818fbb42af rpc error: code = 2 desc = "containerd: container did not start before the specified timeout"`

You will need the following configuration:
```bash
echo """
[Service]
TasksMax=infinity
""" > /etc/systemd/system/docker.service.d/docker.conf
```


Maybe we (@ruiztulio and me) could help you to configure the servers together.

Tell us if is a good idea for you

**Comment by gurneyalex** [comment] 2016-12-02 15:07
we are currently running travis2docker-3.0.9-py2.7.egg and Docker version 1.6.2, build 7c8fca2

**Comment by gurneyalex** [comment] 2016-12-02 15:16
I'll handle the upgrade this week end.

**Comment by gurneyalex** [comment] 2016-12-04 17:28
upgrade done. It took like forever, because of the checksum verification of the images... 

I just relaunched the building of the 9.0 and 10.0 branches.

**Comment by pedrobaeza** [comment] 2016-12-04 19:27
Thanks, I'll check the problematic builds to see if they are fixed.

**Comment by moylop260** [comment] 2016-12-04 20:09
Thanks I rebuilt a few failed builds again...
Expecting good results...

**Comment by pedrobaeza** [comment] 2016-12-04 20:14
I have already a good build, so it seems all is good now!

**Comment by moylop260** [comment] 2016-12-04 20:21
I find a problem with [build/3273740](https://runbot1.odoo-community.org/runbot/build/3273740)

```bash
 ---> bdc93d905cc9
Error removing intermediate container 522770802fed: No such container: 522770802
Step 23 : RUN /bin/bash -c "source /rvm_env.sh && /install"
 ---> Running in cc692127a715
driver failed programming external connectivity on endpoint reverent_euler (024a5b7): failed to update bridge endpoint 024a5b7 to store: failed to update bridge store for object type *bridge.bridgeEndpoint: timeout
```

A clean process is required after upgrade, more info:
https://github.com/docker/compose/issues/3277#issuecomment-247964243

After that a `rm -rf /DOCKER_PATH` and `reboot` O.S.

**Comment by moylop260** [comment] 2016-12-04 20:26
@gurneyalex 
Could you share us the `docker info` output?
(I want to know if the `Storage Driver` is `aufs`)

And `df -T` output?
(I want to know if the `FS type` is `ext4` for docker partition)

**Comment by gurneyalex** [comment] 2016-12-05 07:39
```
$ docker info
Containers: 183
 Running: 16
 Paused: 0
 Stopped: 167
Images: 1319
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1474
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 126.1 GiB
Name: runbot1
ID: WRV3:RCFA:HGBF:45H6:J4LD:LWW2:4R4W:HILR:QAIZ:YL2F:MU6C:FJ5O
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8

$ df -T
Filesystem     Type      1K-blocks      Used  Available Use% Mounted on
/dev/md2       ext4     1917952024 307084508 1513418100  17% /
udev           devtmpfs      10240         0      10240   0% /dev
tmpfs          tmpfs      26454216    407660   26046556   2% /run
tmpfs          tmpfs      66135532     16788   66118744   1% /dev/shm
tmpfs          tmpfs          5120         0       5120   0% /run/lock
tmpfs          tmpfs      66135532         0   66135532   0% /sys/fs/cgroup
/dev/md1       ext3         499236     36143     436895   8% /boot
tmpfs          tmpfs      13227108         0   13227108   0% /run/user/1001
tmpfs          tmpfs      13227108         0   13227108   0% /run/user/0
none           aufs     1917952024 307084508 1513418100  17% /var/lib/docker/aufs/mnt/c1a91e06e050de0039d7a92cd716ded3d0a73167f76f587439ae6ae7ad6bfe2f
none           aufs     1917952024 307084508 1513418100  17% /var/lib/docker/aufs/mnt/f21455c93c547e5bdc25c8426ce6c64ccb7a1834be9a091853fb52dcb0be3322
none           aufs     1917952024 307084508 1513418100  17% /var/lib/docker/aufs/mnt/856a17cc93331ac317685a97ac9599fc4e2f24b5957a6cecae21c3a59d9914d1
none           aufs     1917952024 307084508 1513418100  17% /var/lib/docker/aufs/mnt/7ce0a7720476b123321a72e4c07ca8167eefc37b85523e74f49f88ea8f3e44c8
none           aufs     1917952024 307084508 1513418100  17% /var/lib/docker/aufs/mnt/798fb6df53bc7d54f24e1e94bafa1a09d18ffc8ae739c35290dda62b10fd939e
none           aufs     1917952024 307084508 1513418100  17% /var/lib/docker/aufs/mnt/730c8b5833b15f1ee40406784424dc4176a631cb2a8e2a3869b4794e269b65d5
none           aufs     1917952024 307084508 1513418100  17% /var/lib/docker/aufs/mnt/8f2a123ee53f190cb9d59f813c2604eaccc5b196b7476a81c4b6e2e9b136cde9
none           aufs     1917952024 307084508 1513418100  17% /var/lib/docker/aufs/mnt/0ad64f640635cecf91d4b4cc69fd081da25adf91dbde7df50a9e3994b2825dc6
none           aufs     1917952024 307084508 1513418100  17% /var/lib/docker/aufs/mnt/da9f959c6ec25c6264f5edcc0a5cef8f22abc8af5b16a066bf0a775b39fc343d
none           aufs     1917952024 307084508 1513418100  17% /var/lib/docker/aufs/mnt/3764c5f12f1adb9b5d19a4fcebcb08e6d4da9254410119b46c8e23e5789eb374
none           aufs     1917952024 307084508 1513418100  17% /var/lib/docker/aufs/mnt/89310a2080344475310f4f04566a5a6f8fb7fa377ae96a8d200f30ebdc44427f
none           aufs     1917952024 307084508 1513418100  17% /var/lib/docker/aufs/mnt/ab2a79d2c89d770c9b617596c3a4c6d0ae7f6a1b5beb98d03503396487d17b17
none           aufs     1917952024 307084508 1513418100  17% /var/lib/docker/aufs/mnt/1785b18a23e60519c8d57191bb40f05ecc6b9bb9adf04c0f9666e0f4af7da102
none           aufs     1917952024 307084508 1513418100  17% /var/lib/docker/aufs/mnt/a1273e52f12b69acced091ba23faf80f36e8a1489350bd1dcea7582b1e432d2d
none           aufs     1917952024 307084508 1513418100  17% /var/lib/docker/aufs/mnt/200c00085520a8fca3b1ee1cf58a5ebac827c23b2a2597781060e2cba48298ca
none           aufs     1917952024 307084508 1513418100  17% /var/lib/docker/aufs/mnt/305b8f5c95b69c42152c3a95b570e68bb81801d2e7417fae7bec08acac2736c8

```

**Comment by gurneyalex** [comment] 2016-12-05 07:42
What I did yesterday:

* stop all docker instances on the runbots
* uninstall and purge docker.io  from Debian jessie
* install docker-engine 1.12.3
* stop all remaining non docker instances
* drop all build databases
* run docker-gc
* restart runbot instance
* trigger the rebuilds.

**Comment by moylop260** [comment] 2016-12-05 15:39
Thanks @gurneyalex 
We are using `ext4` and `aufs` too working fine with `docker 1.12.3`

Could you tell us more about `run docker-gc`?
 - Where is that script?
 - Is a schedule running each period?

I have 2 theories:

1. The https://github.com/docker/compose/issues/3277#issuecomment-247964243 has a manual script to clean after upgrade, but I don't know if was ran from `docker-gc`:
```bash
# stop & remove docker containers:
docker stop $(docker ps -a -q); docker rm $(docker ps -a -q); docker volume rm $(docker volume ls -qf dangling=true)
# remove problematic networks:
docker network rm(docker network ls -q)
# find out which process occupies the port
lsof -nP | grep LISTEN

# My additional steps:
rm -rf /DOCKER_PATH
reboot  # Faster stop of occupies port
```

2. If we have a schedule of `docker-gc` maybe could be deleting image/containers early (Before of finish a full runbot-build)

**Comment by gurneyalex** [comment] 2016-12-06 08:13
Hello, docker-gc is https://github.com/spotify/docker-gc which I'm running using the docker image. 

It is *not* run via a cron (as of now). I ran it manually during the upgrade to clean up old builds, while the runbot was not running.

**Comment by lasley** [comment] 2016-12-06 19:05
I don't think it would be `docker-gc` - I have mine (also from Spotify repo) on cron.hourly and it's never caused issues. I'm even using `FORCE_IMAGE_REMOVAL=1`.

I just updated to all same versions we're using in OCA onto my prod Runbot & will be monitoring for these issues. I'm hoping to get the issue replicated local so I can mess around.

**Comment by pedrobaeza** [comment] 2016-12-06 19:27
I have observed that the problem is with 10.0 builds, but not with 9.0

**Comment by moylop260** [comment] 2016-12-07 00:11
I saw the following 10.0 builds:
[server-tools#10.0](https://runbot.odoo-community.org/runbot/build/3274317) 🍏 
[vertical-medical@10.0](https://runbot.odoo-community.org/runbot/build/3274550) 🔴  <- `Nothing to test- exiting early.` All modules are unported yet

**Comment by lasley** [comment] 2016-12-07 02:19
I just found a failing version 9 too, so no go on that theory 😦 

* https://runbot.odoo-community.org/runbot/build/3274559
* From  https://github.com/OCA/vertical-medical/pull/140

**Comment by moylop260** [comment] 2016-12-07 02:27
The unique way that I saw to reproduce a error similar to `/install: line 61: getaddons.py: command not found` is with a script like as `/install`:
```bash
# ... 60 lines here...
getaddons.py
```

![screen shot 2016-12-06 at 8 27 54 pm](https://cloud.githubusercontent.com/assets/6644187/20952450/1384e74e-bbf2-11e6-883b-00d0134508d6.png)

@gurneyalex 
Could you share us the output of the following command running directly in the hosts of runbot, please?
`rgrep -n "getaddons.py" YOUR_PATH/odoo-extra/runbot/static/travis2docker --include=install -B60 -A60`

**Comment by gurneyalex** [comment] 2016-12-07 22:44
@moylop260 The output of this is quite long...

This one is on runbot1:
[grep.txt.gz](https://github.com/OCA/runbot-addons/files/637935/grep.txt.gz)

This one is on runbot2:
[grep2.txt.gz](https://github.com/OCA/runbot-addons/files/637937/grep2.txt.gz)

**Comment by moylop260** [comment] 2016-12-08 06:01
FYI I have created the following PR: https://github.com/OCA/runbot-addons/pull/114 and the following version of t2d [3.0.10](https://pypi.python.org/pypi/travis2docker/3.0.10)

**Comment by moylop260** [comment] 2016-12-08 20:51
Reviewing the files from `rgrep` output (thanks @gurneyalex) I saw that the script files are corrupt by a variable not reseted and items shared.

  - Reset variables from https://github.com/Vauxoo/travis2docker/commit/2b3afcce1b5565c422e54a023f3637f152c6cd9d and https://github.com/Vauxoo/travis2docker/commit/7128cc20145cf703aeeab9d74acb31630dfb89e6
    - Install using `pip install --upgrade travis2docker==3.0.12`

  - Avoid sharing items like as variables, files and environments (sys.args, paths, images, lists) fixed from https://github.com/OCA/runbot-addons/pull/114
    - Custom project used from oca server PR: https://github.com/gurneyalex/runbot-addons/pull/1

Thanks in advance.

**Comment by moylop260** [comment] 2016-12-08 21:07
<s> @gurneyalex 
Could we disable [OCA/OCB](https://github.com/oca/ocb) to build from travis2docker?

FYI I saw that the lines inserted come from this project:
 - https://github.com/OCA/OCB/blob/da7ccde5b619/.travis.yml#L39

But currently t2d is incompatible with this project (WIP) </s>

Forget it @max3903 help me to disable it, thanks

**Comment by moylop260** [comment] 2016-12-09 01:10
For record, this issue was a bug in travis2docker with non-ideal cases.

Previous
======

We have a class with a `my_var` similar to:
```python
class MyClass(object):
     my_var = None

     def my_method(self, error=None):
         for local_variable in range(10, 11):
                self.my_var = local_variable
                assert not error, error
         self.my_var = None
```

Ideal case works fine! 🍏 
```python
obj1 = MyClass()
obj1.my_method("")
print obj1.my_var  # None: Good!
```

But if there is a error the variable is dirty 🔴 
```python
obj2 = MyClass()
obj2.my_method(error="no ideal case")
print obj2.my_var  # It's not None has the value 10 :(
```

We have a non-ideal case in OCA's runbot (e.g. OCA/OCB) and the flaky error was injected.
We can reproduce it running:
`travisfile2dockerfile https://github.com/OCA/OCB.git 10.0`

```bash
Traceback (most recent call last):
  File "travisfile2dockerfile", line 11, in <module>
    sys.exit(main())
  File "travis2docker/cli.py", line 184, in main
    raise InvalidRepoBranchError(msg)
travis2docker.exceptions.InvalidRepoBranchError: The repo or the branch is incorrect value, because It can not got the .travis.yml content from git@github.com:OCA/OCB.git 10.0.
Please, verify access repository,
verify exists url and revision,
verify exists .travis.yml
```

Fixes
====
Then we need the followings fixes:
```diff
class MyClass(object):
-   my_var = None
+ # Fix mutable variable https://github.com/Vauxoo/travis2docker/commit/7128cc2014
+    def __init__(self):
+        self.my_var = None

     def my_method(self, error=None):
+ # Fix reset to start and end: https://github.com/Vauxoo/travis2docker/commit/2b3afcce1b5565c422
+        self.my_var = None
         for local_variable in range(10, 11):
                self.my_var = local_variable
                assert not error, error
         self.my_var = None
```

Add a .travis.yml to oca/ocb#10.0 or disable travis2docker check from runbot. (Disabled by @max3903)

Sorry for this issue and thanks for help.

**Comment by lasley** [comment] 2016-12-09 05:48
Seriously how the hell did you figure this out @moylop260?! I just wanted to drop my wtf, let me know if I can help any 😄

**Comment by moylop260** [comment] 2016-12-09 19:32
Offtopic:
We need help to migrate new global-matrix `.travis.yml` style.
Because we have some projects without the environment variable`TESTS="1"` and runbot is skipping

**Comment by lasley** [comment] 2016-12-09 19:36
Yeah I just ran into that a few days ago. It would be nice if we could get a report of the skipping build branches. Maybe an export from Runbot filtered by skipped, grouped by branch?

**Comment by moylop260** [comment] 2016-12-09 19:44
Maybe our friend @max3903 could help us with that report

**Comment by lasley** [comment] 2016-12-09 20:14
Do we have any sort of mass-commit scripts/framework or anything? I know I've seen mass commits before, which is why I ask.

**Comment by pedrobaeza** [comment] 2016-12-09 20:16
They are done for the occasion. You can take a look to https://github.com/OCA/maintainer-tools/blob/master/tools/migrate_branch.py for example that some changes made on live on GitHub.

**Comment by gurneyalex** [comment] 2017-01-04 08:43
hello all, I'm back from a long and mostly offline vacation which was really needed. 

@moylop260 congratulations for figuring this out and fixing it! :heart_eyes_cat: 

@lasley I usually do these with bash scripts and the help of the clone_everything script in maintainer tools (1. clone everything and then make a loop on all repos and all branches, sed stuff and commit + push).

**Comment by moylop260** [comment] 2017-01-04 13:55
@gurneyalex
In order to close this issue a step is required:
`pip install --upgrade travis2docker`

Could you help us?

**Comment by gurneyalex** [comment] 2017-01-19 13:40
@moylop260 3.0.13  installed

**Comment by moylop260** [comment] 2017-01-19 15:06
Thanks

**Closed as completed by moylop260** 2017-01-19 15:06 UTC
